/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientcommonsw.vue;

import clientcommonsw.ClientCommonSW;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jose-arthur
 */
public class PremierForm extends javax.swing.JFrame {

    /**
     * Creates new form PemierForm
     */
    public PremierForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEntierNP = new javax.swing.JTextField();
        txtResNP1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDecomposer = new javax.swing.JButton();
        txtResNP2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEntierCB1 = new javax.swing.JTextField();
        txtEntierCB2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCombinaison = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 21)); // NOI18N
        jLabel1.setText("Decomposition d'un entier");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Entier");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Facteur Premier");

        btnDecomposer.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnDecomposer.setText("Decomposer");
        btnDecomposer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecomposerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Nombre Premier");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 21)); // NOI18N
        jLabel5.setText("Calcul de Combinaison");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Entier 1");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Entier 2");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Resultat");

        btnCombinaison.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnCombinaison.setText("Combinaison");
        btnCombinaison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombinaisonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtEntierCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEntierCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCombinaison))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(txtEntierNP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDecomposer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtResNP2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResNP1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(238, 238, 238))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEntierNP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtResNP1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResNP2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addComponent(btnDecomposer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEntierCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtEntierCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnCombinaison)
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDecomposerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecomposerActionPerformed
        // TODO add your handling code here:
        ClientCommonSW csw = new ClientCommonSW();
        int nombre;
        String result = "";
        int premier;

        try {
            nombre = Integer.parseInt(txtEntierNP.getText());

            if (nombre >= 0) {

                ArrayList listeNombre = (ArrayList) csw.decompositionNP(nombre);
                premier = listeNombre.size();
                JOptionPane.showMessageDialog(null, "Voulez-vous décomposer " + nombre + " en produit de facteur premier?", "Produit de facteur premier", JOptionPane.INFORMATION_MESSAGE);
                if (premier == 1) {
                    txtResNP2.setText("Vrai");
                } else {
                    txtResNP2.setText("Faux");
                }

                for (int i = 0; i < listeNombre.size(); i++) {
                    result = result.concat(String.valueOf(listeNombre.get(i)));
                    result = result.concat(" ");
                }
                //JOptionPane.showMessageDialog(null, "Voulez-vous decomposer "+nombre +" en prduit de facteur premier?", "Produit de facteur premier",  JOptionPane.INFORMATION_MESSAGE);
                txtResNP1.setText(result);
            }
        } catch (NumberFormatException e) {
            System.out.println("Error put an integer ");
        }
    }//GEN-LAST:event_btnDecomposerActionPerformed

    private void btnCombinaisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombinaisonActionPerformed
        // TODO add your handling code here:
        ClientCommonSW csw = new ClientCommonSW();
        int nombre1, nombre2;
        int resultat;

        try {
            nombre1 = Integer.parseInt(txtEntierCB1.getText());
            nombre2 = Integer.parseInt(txtEntierCB2.getText());

            if (nombre1 >= 0 && nombre2 >= 0) {

                if (nombre1 > nombre2) {
                    resultat = csw.factoriel(nombre1) / (csw.factoriel(nombre2) * csw.factoriel(nombre1 - nombre2));
                    JOptionPane.showMessageDialog(null, "Voulez-vous la combinaison de " + nombre2 + " dans " + nombre1 + "?", "Combinaison", JOptionPane.INFORMATION_MESSAGE);
                    txtResult.setText(String.valueOf(resultat));

                } else if (nombre1 == nombre2) {
                    JOptionPane.showMessageDialog(null, "Voulez-vous la combinaison de " + nombre2 + " dans " + nombre1 + "?", "Combinaison", JOptionPane.INFORMATION_MESSAGE);
                    txtResult.setText(String.valueOf(1));
                } else {
                    JOptionPane.showMessageDialog(null, "Voulez-vous la combinaison de " + nombre2 + " dans " + nombre1 + "?", "Combinaison", JOptionPane.INFORMATION_MESSAGE);
                    txtResult.setText("Error : Entier2 > Entier1");
                }
            }
        } catch (NumberFormatException e) {
            System.out.println("Error put an integer ");
        }
    }//GEN-LAST:event_btnCombinaisonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PremierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PremierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PremierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PremierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PremierForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCombinaison;
    private javax.swing.JButton btnDecomposer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtEntierCB1;
    private javax.swing.JTextField txtEntierCB2;
    private javax.swing.JTextField txtEntierNP;
    private javax.swing.JTextField txtResNP1;
    private javax.swing.JTextField txtResNP2;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
